#cloud-config
package_update: true
package_upgrade: true

groups:
  - docker

users:
  - name: root
  - name: howtosl
    groups: [sudo, docker]
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - git
  - fail2ban
  - ufw
  - certbot
  - python3-certbot-nginx
  - nginx
  - docker.io
  - docker-compose

write_files:
  - path: /etc/fail2ban/jail.local
    content: |
      [sshd]
      enabled = true
      bantime = 3600
      findtime = 600
      maxretry = 3
  
  - path: /etc/nginx/sites-available/howtosl.com
    content: |
      server {
          listen 80;
          server_name howtosl.com www.howtosl.com;
          
          location / {
              proxy_pass http://localhost:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_set_header X-Forwarded-Host $host;
              proxy_set_header X-Forwarded-Port $server_port;
          }
      }

  - path: /etc/ssh/sshd_config.d/hardening.conf
    content: |
      PermitRootLogin yes
      PasswordAuthentication no
      AllowUsers root howtosl

runcmd:
  # Basic security
  - systemctl restart sshd
  - ufw allow OpenSSH
  - ufw allow 'Nginx Full'
  - ufw --force enable
  - systemctl start fail2ban
  - systemctl enable fail2ban

  # Setup Docker
  - systemctl start docker
  - systemctl enable docker

  # Setup Nginx
  - ln -s /etc/nginx/sites-available/howtosl.com /etc/nginx/sites-enabled/
  - rm /etc/nginx/sites-enabled/default
  - systemctl restart nginx

  # Configure UFW
  - ufw allow 22/tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw allow 2376/tcp
  - ufw allow 2377/tcp
  - ufw allow 7946/tcp
  - ufw allow 7946/udp
  - ufw allow 4789/udp

  # Configure Nginx and SSL
  - systemctl enable nginx
  - systemctl start nginx
  - certbot --nginx -d howtosl.com -d www.howtosl.com --non-interactive --agree-tos --email alex@bramox.com

  # Setup project directory and clone repository
  - mkdir -p /opt/howtosl
  - chown howtosl:howtosl /opt/howtosl
  - cd /opt/howtosl
  - git clone https://github.com/bramox/howtoSL.git .
  - git config --global --add safe.directory /opt/howtosl
  - git submodule init
  - git submodule update
  
  # Build and run Docker container
  - docker build -t howtosl .
  - docker run -d --name howtosl -p 8080:80 --restart unless-stopped howtosl

  # Install monitoring agent
  - curl -sSL https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh | bash
  - wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh
  - sh /tmp/netdata-kickstart.sh --non-interactive

final_message: "The system is finally up, after $UPTIME seconds"
