#cloud-config
package_update: true
package_upgrade: true

groups:
  - docker

users:
  - name: howtosl
    groups: [sudo, docker]
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ${ssh_public_key}

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - git
  - fail2ban
  - ufw
  - certbot
  - python3-certbot-nginx
  - nginx

write_files:
  - path: /etc/fail2ban/jail.local
    content: |
      [sshd]
      enabled = true
      bantime = 3600
      findtime = 600
      maxretry = 3
  
  - path: /etc/nginx/sites-available/howtosl.com
    content: |
      server {
          listen 80;
          server_name ${domain_name} www.${domain_name};
          
          location / {
              proxy_pass http://localhost:1313;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }

  - path: /etc/ssh/sshd_config.d/hardening.conf
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      AllowUsers howtosl

runcmd:
  # Basic security
  - systemctl restart sshd
  
  # Install Docker
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  - systemctl enable docker
  - systemctl start docker
  
  # Install Docker Compose
  - curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

  # Configure UFW
  - ufw allow 22/tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw --force enable

  # Configure fail2ban
  - systemctl enable fail2ban
  - systemctl start fail2ban

  # Configure Nginx and SSL
  - systemctl enable nginx
  - systemctl start nginx
  - ln -s /etc/nginx/sites-available/howtosl.com /etc/nginx/sites-enabled/
  - rm /etc/nginx/sites-enabled/default
  - systemctl restart nginx
  - certbot --nginx -d ${domain_name} -d www.${domain_name} --non-interactive --agree-tos --email ${admin_email}

  # Setup project directory
  - mkdir -p /opt/howtosl
  - chown -R howtosl:howtosl /opt/howtosl

  # Clone and setup the project
  - su - howtosl -c "git clone https://github.com/yourusername/howtosl.git /opt/howtosl"
  - cd /opt/howtosl
  - docker-compose up -d

  # Install monitoring agent
  - curl -sSL https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh | bash
  - wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh
  - sh /tmp/netdata-kickstart.sh --non-interactive

final_message: "The system is finally up, after $UPTIME seconds"
