version: '3'
services:
  hugo:
    image: klakegg/hugo:0.101.0-alpine
    command: server --bind 0.0.0.0 --baseURL https://howtosl.com/
    volumes:
      - .:/src
    ports:
      - "1313:1313"
    environment:
      - HUGO_WATCH=true
      - HUGO_ENV=production
